## 行列を用いたニューラルネットワークの実装

### シンプルな場合

バイアスと活性化関数は無視し、重みだけがある場合を考える

In [5]:
import numpy as np

- 第0層は、$x_1$と$x_2$の２つ → 配列 ```X``` に格納
- 第1層は、$y_1$、$y_2$、$y_3$の３つ → 出力は配列 ```Y```
  - $y_1 = w_{11} x_1 + w_{21} x_2$ などと計算
- 重みは、$w_{11}$、$w_{21}$、$w_{12}$、$w_{22}$、$w_{13}$、$w_{23}$の６つ → 行列 ```W``` に格納

In [6]:
# 第0層を表す配列X
X = np.array([1,2])
print('X: ')
print(X)

# 重みを表す配列W
W = np.array([[1,3,5], [2,4,6]])
print('\nW: ')
print(W)

X: 
[1 2]

W: 
[[1 3 5]
 [2 4 6]]


In [7]:
# 出力層を表す配列Yを計算
Y = np.dot(X, W)
print(Y)

[ 5 11 17]
