## NDArray の使い方


In [95]:
import numpy as np

### 基本的な使い方


In [96]:
# 一次元配列
A = np.array([1, 2, 3, 4])

# Aを出力
print(A)

# Aの次元を出力
print(np.ndim(A))

# Aの形状を出力
print(A.shape)

[1 2 3 4]
1
(4,)


In [97]:
# 二次元配列
B = np.array([[1, 2], [3, 4], [5, 6]])

# Bを出力
print(B)

# Bの次元を出力
print(np.ndim(B))

# Bの形状を出力
print(B.shape)

[[1 2]
 [3 4]
 [5 6]]
2
(3, 2)


### 行列計算


In [98]:
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])

# AとBの行列積を計算
print(np.dot(A, B))

# AとBの要素ごとの積を計算
print(A * B)

[[19 22]
 [43 50]]
[[ 5 12]
 [21 32]]


### 配列に適用できる活性化関数


In [99]:
# テストに使う配列を用意しておく
x = np.arange(11) - 5
print(x)

[-5 -4 -3 -2 -1  0  1  2  3  4  5]


In [100]:
# ステップ関数
def stepFunction(x: np.ndarray):
    y = x > 0
    return y.astype(np.int_)

print(stepFunction(x))

[0 0 0 0 0 0 1 1 1 1 1]


In [101]:
# シグモイド関数
def sigmoid(x: np.ndarray):
    return 1 / (1 + np.exp(-x))

print(sigmoid(x))

[0.00669285 0.01798621 0.04742587 0.11920292 0.26894142 0.5
 0.73105858 0.88079708 0.95257413 0.98201379 0.99330715]


In [102]:
# ReLU関数
def relu(x: np.ndarray):
    return np.maximum(0, x)

print(relu(x))

[0 0 0 0 0 0 1 2 3 4 5]
