## Softmax関数の実装

出力は0〜1、出力の総和は1となるので、確率として解釈できる。
softmax関数を通してもニューロンどうしの大小関係は変わらないので、単に最大のニューロンを分類結果として利用し、softmax関数を省略することも一般的（```exp```の計算にコストがかかるため）

### 単純な実装

In [3]:
import numpy as np

In [4]:
def softmax(a: np.ndarray) -> np.ndarray:
    exp_a = np.exp(a)
    y = exp_a / np.sum(exp_a)
    return y

# 小さい数値ならオーバーフローを起こす心配はない
print(softmax(np.array([0.3,2.9,4.0])))

# 大きい数値だとオーバーフローする
print(softmax(np.array([1010,1000,990])))

[0.01821127 0.24519181 0.73659691]
[nan nan nan]


/tmp/ipykernel_8594/3591856642.py:2: RuntimeWarning: overflow encountered in exp
  exp_a = np.exp(a)
/tmp/ipykernel_8594/3591856642.py:3: RuntimeWarning: invalid value encountered in divide
  y = exp_a / np.sum(exp_a)


### オーバーフロー対策を考慮した実装

$y_k = \frac{\exp(a_k - a_{\text{max}})}{\sum_{i=1}^n \exp (a_i - a_{\text{max}})}$ として、大きな数の指数関数をとることによるオーバーフローを防ぐ

In [5]:
def softmax(a: np.ndarray) -> np.ndarray:
    c = np.max(a)
    exp_a = np.exp(a - c)
    y = exp_a / np.sum(exp_a)
    return y

# 小さい数値なら先ほどと同様の結果に
print(softmax(np.array([0.3,2.9,4.0])))

# 大きい数値でもオーバーフローしない
print(softmax(np.array([1010,1000,990])))

[0.01821127 0.24519181 0.73659691]
[9.99954600e-01 4.53978686e-05 2.06106005e-09]
